export const WORKSPACE = {
  ADMIN_PANEL: process.env.ADMIN_PANEL_WORKSPACE_BASE_URL,
  MEMBER_MANAGEMENT: process.env.MEMBER_MANAGEMENT_WORKSPACE_BASE_URL,
};

export const COMMUNITY = {
  ADMIN_PANEL_PRIVATE: process.env.ADMIN_PANEL_PRIVATE_COMMUNITY_KEY,
  ADMIN_PANEL_PUBLIC: process.env.ADMIN_PANEL_PUBLIC_COMMUNITY_KEY
};
